const data = [
  {
    id: 1,
    title: "Product Designer",
    title1: "Product",
    title2: "Designer",
    desc: "Product Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "A I develop the user interface.",
    info2: "B Web page development.",
    info3: "C I create ux element interactions.",
    info4: "D I position your company brand.",
    info5: "E Design and mockups of products for companies.",
  },
  {
    id: 2,
    title: "Ui/Ux Designer",
    title1: "Ui/Ux",
    title2: "Designer",
    desc: "Ui/Ux Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "F I develop the user interface.",
    info2: "G Web page development.",
    info3: "H I create ux element interactions.",
    info4: "I position your company brand.",
    info5: "J Design and mockups of products for companies.",
  },
  {
    id: 3,
    title: "Visual Designer",
    title1: "Visual",
    title2: "Designer",
    desc: "Visual Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "K I develop the user interface.",
    info2: "L Web page development.",
    info3: "M I create ux element interactions.",
    info4: "N I position your company brand.",
    info5: "O Design and mockups of products for companies.",
  },
  {
    id: 4,
    title: "Prout Designer",
    title1: "Prout",
    title2: "Designer",
    desc: "Prout Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "P I develop the user interface.",
    info2: "Q Web page development.",
    info3: "R I create ux element interactions.",
    info4: "S I position your company brand.",
    info5: "T Design and mockups of products for companies.",
  },
  {
    id: 5,
    title: "Prout Designer",
    title1: "Prout",
    title2: "Designer",
    desc: "Prout Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "P I develop the user interface.",
    info2: "Q Web page development.",
    info3: "R I create ux element interactions.",
    info4: "S I position your company brand.",
    info5: "T Design and mockups of products for companies.",
  },
  {
    id: 6,
    title: "Prout Designer",
    title1: "Prout",
    title2: "Designer",
    desc: "Prout Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "P I develop the user interface.",
    info2: "Q Web page development.",
    info3: "R I create ux element interactions.",
    info4: "S I position your company brand.",
    info5: "T Design and mockups of products for companies.",
  },
];

export default data;
