// Ajouter cartes infos aux cartes, disposer carte dans le bon ordre

const data = [
  {
    id: 1,
    title: "Site Vitrine",
    title1: "Site",
    title2: "Vitrine",
    desc: "Valorisez votre entreprise en optant pour un site vitrine conçu pour séduire.",
    info1: "Design Moderne, Épuré & Professionnel",
    info2: "Mise en avant de vos Produits & Services",
    info3: "Optimisé pour Ordinateurs & Smartphones",
    info4: "Flexibilité, Fonctionnalités sur-mesure",
    info5: "Suivi Continu et Maintenance Simplifiée",
  },
  {
    id: 2,
    title: "Frontend Intégrateur",
    title1: "Frontend",
    title2: "Dev",
    desc: "Ui/Ux Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "F I develop the user interface.",
    info2: "G Web page development.",
    info3: "H I create ux element interactions.",
    info4: "I position your company brand.",
    info5: "J Design and mockups of products for companies.",
  },
  {
    id: 3,
    title: "API Designer",
    title1: "API",
    title2: "Design",
    desc: "Visual Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "K I develop the user interface.",
    info2: "L Web page development.",
    info3: "M I create ux element interactions.",
    info4: "N I position your company brand.",
    info5: "O Design and mockups of products for companies.",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    title1: "UI/UX",
    title2: "Design",
    desc: "Visual Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "K I develop the user interface.",
    info2: "L Web page development.",
    info3: "M I create ux element interactions.",
    info4: "N I position your company brand.",
    info5: "O Design and mockups of products for companies.",
  },
  {
    id: 5,
    title: "UI/UX Designer",
    title1: "FullStack",
    title2: "App",
    desc: "Visual Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "K I develop the user interface.",
    info2: "L Web page development.",
    info3: "M I create ux element interactions.",
    info4: "N I position your company brand.",
    info5: "O Design and mockups of products for companies.",
  },
  {
    id: 6,
    title: "WordPress",
    title1: "WordPress",
    title2: "Dev",
    desc: "Visual Service with more than 3 years of experience. Providing quality work to clients and companies.",
    info1: "K I develop the user interface.",
    info2: "L Web page development.",
    info3: "M I create ux element interactions.",
    info4: "N I position your company brand.",
    info5: "O Design and mockups of products for companies.",
  },
];

export default data;
