export const skillsData = [
  {
    id: 1,
    cat: "Frontend",
    name1: "React",
    desc1: "Avancé",
    name2: "Tailwind",
    desc2: "Avancé",
    name3: "Bootstrap",
    desc3: "Avancé",
    name4: "NextJS",
    desc4: "Avancé",
    name5: "Typescript",
    desc5: "Intermédiaire",
    name6: "Astro",
    desc6: "Intermédiaire",
  },
  {
    id: 2,
    cat: "Backend",
    name1: "Node.js",
    desc1: "Intermédiaire",
    name2: "MongoDB",
    desc2: "Avancé",
    name3: "MySQL",
    desc3: "Intermédiaire",
    name4: "Express",
    desc4: "Intermédiaire",
    name5: "GraphQL",
    desc5: "Intermédiaire",
    name6: "Sanity",
    desc6: "Intermédiaire",
  },
  {
    id: 3,
    cat: "Outils",
    name1: "ChatGPT",
    desc1: "Avancé",
    name2: "Midjourney",
    desc2: "Avancé",
    name3: "Photoshop",
    desc3: "Avancé",
    name4: "Git",
    desc4: "Avancé",
    name5: "Copilot",
    desc5: "Avancé",
    name6: "Figma",
    desc6: "Avancé",
  },

  // Add 4th card "Soft Skills" no one thinks about that
];

export const certifsData = [
  {
    id: 1,
    cat: "Certificats",
    name1: "Web Developer",
    desc1: "OpenClassrooms | 2022",
    link1: "/pdf/certif-1.pdf",
    name2: "Responsive Design",
    desc2: "FreeCodeCamp | 2023",
    link2: "",
    name3: "JS Algorithms",
    desc3: "FreeCodeCamp | 2023",
    link3: "",
    name4: "Front End Development Libraries",
    desc4: "FreeCodeCamp | 2023",
    link4: "",
    name5: "Back End Development and APIs",
    desc5: "FreeCodeCamp | 2023",
    link5: "",
  },
];
