export const skillsData = [
  {
    id: 1,
    cat: "Frontend",
    name1: "HTML",
    desc1: "Avancé",
    name2: "CSS",
    desc2: "Avancé",
    name3: "Javascript",
    desc3: "Avancé",
    name4: "React",
    desc4: "Avancé",
    name5: "Angular",
    desc5: "Avancé",
    name6: "Vue",
    desc6: "Avancé",
  },
  {
    id: 2,
    cat: "Backend",
    name1: "HTML",
    desc1: "Avancé",
    name2: "CSS",
    desc2: "Avancé",
    name3: "Javascript",
    desc3: "Avancé",
    name4: "React",
    desc4: "Avancé",
    name5: "Angular",
    desc5: "Avancé",
    name6: "Vue",
    desc6: "Avancé",
  },
  {
    id: 3,
    cat: "More",
    name1: "HTML",
    desc1: "Avancé",
    name2: "CSS",
    desc2: "Avancé",
    name3: "Javascript",
    desc3: "Avancé",
    name4: "React",
    desc4: "Avancé",
    name5: "Angular",
    desc5: "Avancé",
    name6: "Vue",
    desc6: "Avancé",
  },
];

export const certifsData = [
  {
    id: 1,
    cat: "Certificates",
    name1: "Web Developer",
    desc1: "OpenClassrooms | 2022",
    link1: "/pdf/certif-oc-webdev.pdf",
    name2: "Responsive Design",
    desc2: "FreeCodeCamp | 2023",
    link2: "",
    name3: "JS Algorithms",
    desc3: "FreeCodeCamp | 2023",
    link3: "",
    name4: "Front End Development Libraries",
    desc4: "FreeCodeCamp | 2023",
    link4: "",
    name5: "Back End Development and APIs",
    desc5: "FreeCodeCamp | 2023",
    link5: "",
  },
];
