// un map pour les cartes, juste un tableau avec les titres des cartes et id pour avoir le bon nombre de cartes
//

const skills = [
  {
    id: 1,
    title: "Frontend",
    skill1: "HTML",
    exp1: "Avancé",
    skill2: "CSS",
    exp2: "Avancé",
    skill3: "Javascript",
    exp3: "Avancé",
    skill4: "React",
    exp4: "Avancé",
    skill5: "Angular",
    exp5: "Avancé",
    skill6: "Vue",
    exp6: "Avancé",
  },
  {
    id: 2,
    title: "Backend",
    skill1: "HTML",
    exp1: "Avancé",
    skill2: "CSS",
    exp2: "Avancé",
    skill3: "Javascript",
    exp3: "Avancé",
    skill4: "React",
    exp4: "Avancé",
    skill5: "Angular",
    exp5: "Avancé",
    skill6: "Vue",
    exp6: "Avancé",
  },
  {
    id: 3,
    title: "More",
    skill1: "HTML",
    exp1: "Avancé",
    skill2: "CSS",
    exp2: "Avancé",
    skill3: "Javascript",
    exp3: "Avancé",
    skill4: "React",
    exp4: "Avancé",
    skill5: "Angular",
    exp5: "Avancé",
    skill6: "Vue",
    exp6: "Avancé",
  },
];
const certifs = [
  {
    id: 1,
    title: "Certificates",
    certif1: "Web Developer",
    school1: "OpenClassrooms | 2022",
    link1: "",
    certif2: "Responsive Web Design",
    school2: "FreeCodeCamp | 2023",
    link2: "",
    certif3: "JS Algorithms, Data Structures",
    school3: "FreeCodeCamp | 2023",
    link3: "",
    certif4: "Front End Development Libraries",
    school4: "FreeCodeCamp | 2023",
    link4: "",
    certif5: "Back End Development and APIs",
    school5: "FreeCodeCamp | 2023",
    link5: "",
  },
];

export default { skills, certifs };
