// TODO: Categories to add : WordPress, Mobile, E-Commerce

import img from "../../assets/img";

const data = [
  {
    id: 1,
    name: "Dribbble clone",
    img: img.work1,
    link: "https://github.com/basedhound",
    cat: "Fullstack",
    fav: true,
  },
  {
    id: 2,
    name: "Test 1",
    img: img.work1,
    link: "https://github.com/basedhound",
    cat: "Fullstack",
    fav: false,
  },
  {
    id: 3,
    name: "Test 1",
    img: img.work1,
    link: "https://github.com/basedhound",
    cat: "Fullstack",
    fav: false,
  },

  {
    id: 4,
    name: "Test 2",
    img: img.work2,
    link: "https://github.com/basedhound",
    cat: "Frontend",
    fav: false,
  },
  {
    id: 5,
    name: "Test 2",
    img: img.work2,
    link: "https://github.com/basedhound",
    cat: "Frontend",
    fav: false,
  },
  {
    id: 6,
    name: "Test 2",
    img: img.work2,
    link: "https://github.com/basedhound",
    cat: "Frontend",
    fav: false,
  },
  {
    id: 7,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "API",
    fav: false,
  },
  {
    id: 8,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "API",
    fav: false,
  },
  {
    id: 9,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "API",
    fav: false,
  },
  {
    id: 10,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "E-Commerce",
    fav: false,
  },
  {
    id: 11,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "E-Commerce",
    fav: false,
  },
  {
    id: 12,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "E-Commerce",
    fav: false,
  },
  {
    id: 13,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "WordPress",
    fav: false,
  },
  {
    id: 14,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "WordPress",
    fav: false,
  },
  {
    id: 15,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "WordPress",
    fav: false,
  },
  {
    id: 16,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "E-Commerce",
    fav: false,
  },
  {
    id: 17,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "E-Commerce",
    fav: false,
  },
  {
    id: 18,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "E-Commerce",
    fav: false,
  },
  {
    id: 19,
    name: "Test 3",
    img: img.work3,
    link: "https://github.com/basedhound",
    cat: "Mobile",
    fav: false,
  },


];

export default data;
